name: Build and Archive

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: 'Create env file'
        run: |
          touch .env
          echo DATABASE_URL=$DATABASE_URL >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          cat .env
      - run: npx pnpm i --frozen-lockfile
      - run: npx pnpm build:all
      - uses: actions/upload-artifact@v3
        with:
          name: api
          path: dist/apps/api
      - uses: actions/upload-artifact@v3
        with:
          name: ui
          path: dist/apps/ui
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download ui
        uses: actions/download-artifact@v1
        with:
          name: ui
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ui
